### ISSUE TITLE
Problems with the Core

### ISSUE THREAD

**Issue by GonzaloFajardoMedina** [fp7-netide/Engine#102]
Hello,
when I run the command "log:tail" in Karaf, it reports the next errors:
![core1](https://cloud.githubusercontent.com/assets/11718117/16156044/8c637f76-34b2-11e6-93fc-21236e392e03.png)
![core2](https://cloud.githubusercontent.com/assets/11718117/16156043/8c627cf2-34b2-11e6-9c63-36fb826b4be5.png)
![core3](https://cloud.githubusercontent.com/assets/11718117/16156045/8c66b09c-34b2-11e6-9076-3e31f5aa4932.png)

any solution?
Thanks.

**Comment by schwabe** [comment]
The 2nd stacktrace is file not found or something similar the the 3rd picture is a result of the failed 2nd picture. The first one, no idea. There are not even classes of us in the trace.

**Comment by GonzaloFajardoMedina** [comment]
Thanks @schwabe . I think the 2nd and 3rd problem is because it doesn't load properly the composition file, but the first... I don't know why. So, at the moment I can't connect the Core correctly... I have to continue researching.

**Comment by schwabe** [comment]
Do you have a second karaf/onos/old running? Might be duplicate ports.

**Comment by GonzaloFajardoMedina** [comment]
No, all closed.

**Comment by amarsico** [comment]
Hi all, the problem seems related to the Karaf version. I've never seen such stacktrace. Please try to run a clean Karaf 3.0.5 with the command `karaf clean`.
