### ISSUE TITLE
update is needed in the Core

### ISSUE THREAD

**Issue by sergiotamu** [fp7-netide/Engine#103]
I have made a clean installation of the Engine in a VM and I have detected a problem in the Core. The other day Roberto updated the netip library (for python) and now the netide protocol version 1.3. has the value 0x04.

The problem is that the core does not expect this value on the NetIDE header. In the NetIDEProtocolVersion.java It is necessary to add a couple of lines:

---

public enum NetIDEProtocolVersion {
    /**
     \* The Version 1.0
     _/
    VERSION_1_0((byte) 0x01),
    /_*
     \* The Version 1.1
     _/
    VERSION_1_1((byte) 0x02),
    /_*
     \* The Version 1.2
     _/
    VERSION_1_2((byte) 0x03)__,
    /_*
     \* The Version 1.3
     _/
    VERSION_1_3((byte) 0x04);_*

---

 I don't know if it is necessary to change something more... 
Therefore I assign this issue to Roberto and Arne =)

**Comment by ralvarep** [comment]
I have the same problem as @sergiotamu. The core log shows the following:

`2016-06-20 14:06:03,025 | ERROR | tor Receive Loop | ShimManager                      | 145 - core.connectivity - 1.1.0.SNAPSHOT | Unable to parse received data from 'shim' ([4, 17, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 8, 0, 0, 0, 0]).
java.lang.IllegalArgumentException: Unexpected value 4`

Thanks!
