### ISSUE TITLE
Problem with the core

### ISSUE THREAD

**Issue by sergiotamu** [fp7-netide/Engine#105]
Hello @schwabe  and @amarsico ,

I have made another clean installation and I found some problems with the core. I have pulled the latest code and I have recompile the Core without any problem. Then, I have made a clean installation of the core with "bin/karaf clean" and then I have introduced "feature:repo-add mvn:eu.netide.core/core.features/1.1.0-SNAPSHOT/xml/features". However, after this step I have installed the core with the command "feature:install core" and I have taken a look to the log with "log:tail" where I have found the following error message:

> 2016-06-23 17:40:24,450 | ERROR | pool-9-thread-1  | WebAppPublisher                  | 121 - org.ops4j.pax.web.pax-web-extender-war - 3.2.6 | Error deploying web application
> java.lang.IllegalStateException: No LoginService for org.eclipse.jetty.security.authentication.BasicAuthenticator@2f257854 in org.eclipse.jetty.security.ConstraintSecurityHandler@30b96f45
>     at org.eclipse.jetty.security.authentication.LoginAuthenticator.setConfiguration(LoginAuthenticator.java:61)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
>     at org.eclipse.jetty.security.SecurityHandler.doStart(SecurityHandler.java:377)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
>     at org.eclipse.jetty.security.ConstraintSecurityHandler.doStart(ConstraintSecurityHandler.java:453)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
>     at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
>     at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
>     at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:115)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
>     at org.eclipse.jetty.server.session.SessionHandler.doStart(SessionHandler.java:124)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
>     at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
>     at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
>     at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:115)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
>     at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:763)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
>     at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
>     at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
>     at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doStart(HttpServiceContext.java:222)[116:org.ops4j.pax.web.pax-web-jetty:3.2.6]
>     at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
>     at org.ops4j.pax.web.service.jetty.internal.JettyServerImpl$1.start(JettyServerImpl.java:204)[116:org.ops4j.pax.web.pax-web-jetty:3.2.6]
>     at org.ops4j.pax.web.service.internal.HttpServiceStarted.end(HttpServiceStarted.java:1032)[115:org.ops4j.pax.web.pax-web-runtime:3.2.6]
>     at org.ops4j.pax.web.service.internal.HttpServiceProxy.end(HttpServiceProxy.java:422)[115:org.ops4j.pax.web.pax-web-runtime:3.2.6]
>     at org.ops4j.pax.web.extender.war.internal.RegisterWebAppVisitorWC.end(RegisterWebAppVisitorWC.java:341)[121:org.ops4j.pax.web.pax-web-extender-war:3.2.6]
>     at org.ops4j.pax.web.extender.war.internal.model.WebApp.accept(WebApp.java:678)[121:org.ops4j.pax.web.pax-web-extender-war:3.2.6]
>     at org.ops4j.pax.web.extender.war.internal.WebAppPublisher$WebAppDependencyListener.register(WebAppPublisher.java:237)[121:org.ops4j.pax.web.pax-web-extender-war:3.2.6]
>     at org.ops4j.pax.web.extender.war.internal.WebAppPublisher$WebAppDependencyListener.addingService(WebAppPublisher.java:182)[121:org.ops4j.pax.web.pax-web-extender-war:3.2.6]
>     at org.ops4j.pax.web.extender.war.internal.WebAppPublisher$WebAppDependencyListener.addingService(WebAppPublisher.java:135)[121:org.ops4j.pax.web.pax-web-extender-war:3.2.6]
>     at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:932)[karaf-org.osgi.core.jar:]
>     at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:864)[karaf-org.osgi.core.jar:]
>     at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)[karaf-org.osgi.core.jar:]
>     at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)[karaf-org.osgi.core.jar:]
>     at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:317)[karaf-org.osgi.core.jar:]
>     at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261)[karaf-org.osgi.core.jar:]
>     at org.ops4j.pax.web.extender.war.internal.WebAppPublisher.publish(WebAppPublisher.java:101)[121:org.ops4j.pax.web.pax-web-extender-war:3.2.6]
>     at org.ops4j.pax.web.extender.war.internal.WebObserver.deploy(WebObserver.java:213)[121:org.ops4j.pax.web.pax-web-extender-war:3.2.6]
>     at org.ops4j.pax.web.extender.war.internal.WebObserver$1.doStart(WebObserver.java:175)[121:org.ops4j.pax.web.pax-web-extender-war:3.2.6]
>     at org.ops4j.pax.web.extender.war.internal.extender.SimpleExtension.start(SimpleExtension.java:58)[121:org.ops4j.pax.web.pax-web-extender-war:3.2.6]
>     at org.ops4j.pax.web.extender.war.internal.extender.AbstractExtender$1.run(AbstractExtender.java:266)[121:org.ops4j.pax.web.pax-web-extender-war:3.2.6]
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_91]
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_91]
>     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_91]
>     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_91]
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_91]
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_91]
>     at java.lang.Thread.run(Thread.java:745)[:1.8.0_91]

Once the core was running, I have deployed the Ryu shim, the Ryu backend and mininet. And the Backend is all the time waiting for completing the handshake. Again I have taken a look to the Core log and I could see this new error:

> 2016-06-23 17:36:29,292 | ERROR | pool-13-thread-1 | CompositionManager               | 146 - core.caos - 1.1.0.SNAPSHOT | An exception occurred while handling shim message.
> java.lang.NoClassDefFoundError: Could not initialize class eu.netide.core.caos.execution.FlowExecutors
> at eu.netide.core.caos.CompositionManager.processShimMessage(CompositionManager.java:140)
> at Proxyed8cb17a_8dc0_42ec_94c9_0e71fa264750.processShimMessage(Unknown Source)
> at eu.netide.core.globalfib.FIBManager.OnShimMessage(FIBManager.java:60)
> at Proxyefed8c53_5600_4f9b_9dd1_3aff44b96d75.OnShimMessage(Unknown Source)
> at eu.netide.core.connectivity.ShimManager.lambda$OnDataReceived$1(ShimManager.java:78)
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_91]
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_91]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_91]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_91]
> at java.lang.Thread.run(Thread.java:745)[:1.8.0_91]

Anybody knows what is happening in the Core??

Best Regards,
Sergio

**Comment by ralvarep** [comment]
I have tested the latest commit and I have exactly the same problem as @sergiotamu.

**Comment by GonzaloFajardoMedina** [comment]
Hi everybody,
I have the same error that @ralvarep and @sergiotamu say.
any suggestion, @amarsico and @schwabe ?
Thanks

**Comment by schwabe** [comment]
kann you check if all modules have been installed in karaf and what their status is? E.g.

```
netide-core>bundle:list  |grep core
 89 | Active |  80 | 2.7.0          | Jackson-core                         
133 | Active |  80 | 1.19.0         | jersey-core                          
144 | Active |  80 | 1.1.0.SNAPSHOT | core.api Bundle                      
145 | Active |  80 | 1.1.0.SNAPSHOT | core.connectivity Bundle             
146 | Active |  80 | 1.1.0.SNAPSHOT | core.caos Bundle                     
147 | Active |  80 | 1.1.0.SNAPSHOT | core.logpub Bundle                   
148 | Active |  80 | 1.1.0.SNAPSHOT | core.globalfib Bundle                
149 | Active |  80 | 1.1.0.SNAPSHOT | core.management Bundle               
netide-core>
```

**Comment by ralvarep** [comment]
Hi @schwabe,

I have the same modules installed in the core as you. I attach the next image:
![captura de pantalla de 2016-06-24 15 10 44](https://cloud.githubusercontent.com/assets/3491919/16338576/ec0494c2-3a1d-11e6-8b00-6978ccb46de7.png)

**Comment by sergiotamu** [comment]
Hello @schwabe ,

I have tested your latest commit and when I install the core in karaf I still have the same error I explained in my previous email. However, this error does not stop the execution of the core. So when I connect the rest of the components (Ryu backend, Ryu shim and mininet) I don't receive any error this time!.

So, I have tried to make a ping between the hosts and it does not work. I don't know the reason but there is no connectivity between the hosts.

I reopen the issue

**Comment by GonzaloFajardoMedina** [comment]
Hi @schwabe, @sergiotamu, @ralvarep and @amarsico,
I am having the same problem. I have added the new dependency, although all works and I can connect all, hosts are not reached between them.
what could it be?
Thanks.

**Comment by GonzaloFajardoMedina** [comment]
The core reports the next error:
![core](https://cloud.githubusercontent.com/assets/11718117/16382479/3a815102-3c81-11e6-89c3-914ae3e04e80.png)

any suggestion? Thanks.

**Comment by sergiotamu** [comment]
I think the last error is because the backend and the applications that are executed on top of it have been not connected yet to the rest of the Engine. Once you execute the backend this error is removed.

**Comment by ralvarep** [comment]
Hi @GonzaloFajardoMedina, I think that the error you show is because you don't have loaded the backends (Firewall in your case). Try to execute _netide:listmodules_ and check that you have the firewall running.

**Comment by GonzaloFajardoMedina** [comment]
When I type listmodules in the Core, we can check firewall is running. Look the next image:
![firewall](https://cloud.githubusercontent.com/assets/11718117/16382842/cdd86638-3c82-11e6-8753-62d250001f2e.png)

Thanks.

**Comment by sergiotamu** [comment]
I think these errors are previous to the excution of the backend. Once you run the backend the errors dissapear.

**Comment by ralvarep** [comment]
In your image I think you don't have any firewall in backend running properly. It seems that you have connected Ryu backend but you don't have connected neither switch nor firewall.

Look my modules:
![captura de pantalla de 2016-06-27 16 28 05](https://cloud.githubusercontent.com/assets/3491919/16383151/2aa29eb4-3c84-11e6-9918-522caf311361.png)
They are connected and you can see that they have a little time from the last message (less than 5 sec).

**Comment by schwabe** [comment]
I am closing again because the discussion is mixed all kind of problems. The primary bug here is fixes (IPaket not found)> For any remaining feel free to open a new a new bug. 

The Firewall bug is strange but please start with a fresh karaf instance and see if it persists.
