### ISSUE TITLE
Error compiling Java Core (core.routing module)

### ISSUE THREAD

**Issue by ralvarep** [fp7-netide/Engine#106]
I am trying to compile the latest commit of Java Core with Java 8 (Oracle) and it fails.

The error is the following:
![captura de pantalla de 2016-06-28 16 22 09](https://cloud.githubusercontent.com/assets/3491919/16419022/7d96e472-3d4c-11e6-8fdb-c1892caf63b0.png)

Any idea? Thanks!

**Comment by schwabe** [comment]
Yeah that code is at the moment work in progress.

**Comment by schwabe** [comment]
Just go back before a revision with the changes (i.e. anything from yesterday). I will fix the bugs tommorrow

**Comment by ralvarep** [comment]
Ok @schwabe , when you upload the changes, I will try it again to check that it is working.
