### ISSUE TITLE
Problems with Ryu-backend

### ISSUE THREAD

**Issue by GonzaloFajardoMedina** [fp7-netide/Engine#109]
Hi everybody,
I have been testing the new changes, it looks well, but I have the next error:
![error-backend](https://cloud.githubusercontent.com/assets/11718117/16665395/bef7b9d0-4483-11e6-9197-b3b51b5240e5.png)

any suggestion?

Thanks.

**Comment by doriguzzi** [comment]
This happens when you mix different versions of OpenFlow. Please check that applications and mininet are using the same version.

**Comment by ElisaRojas** [comment]
I was just about to say the same thing as Roberto. @GonzaloFajardoMedina , please check that.

**Comment by GonzaloFajardoMedina** [comment]
Thanks @doriguzzi and @ElisaRojas for the answer.
I will close this.

**Comment by doriguzzi** [comment]
@GonzaloFajardoMedina I'm having the same problem when running mininet with the UC2_IITSystem.py script. However, I'm not able to find a way to modify that script in order to force Mininet to use OF10 only. It always negotiates 1.3 with the Shim, and this makes the ryu-backend crashing when running IITS_NetManager.py atop. How did you solve this problem?

Thanks in advance.

**Comment by GonzaloFajardoMedina** [comment]
Hi @doriguzzi ,
I used the same script, but I changed the OpenFlow version to adapt to specifications script.
I didn't change the script, so I don't know how change it. Let me try a thing and I'll tell.
Thanks,

**Comment by ElisaRojas** [comment]
Hi @doriguzzi , this is more related to UC2 maybe :)

You can use a specific version of OF by setting: 

```
addSwitch('s1',protocols='OpenFlow13')
```

for OF1.3... or:

```
addSwitch('s1',protocols='OpenFlow10')
```

for OF1.0.
(This should be done for every switch, currently it only runs addSwitch with no config parameters).

I think it's a good point and maybe we should add it to the script as a parameter. I'll close this issue and open a new one in the UseCases repo for this, thank you!
