### ISSUE TITLE
Error building ODL

### ISSUE THREAD

**Issue by kjrrp** [fp7-netide/Engine#11]
Hi,

I have this error when trying to go through the tutorial.

<pre>
Now, navigate to Engine/odl-shim and perform mvn clean install
</pre>

mvn clean install
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.opendaylight.openflowplugin:pyretic-odl:0.0.6-Helium-SR3 (/home/tai/git/Engine/odl-shim/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find org.opendaylight.openflowplugin:openflowplugin-parent:pom:0.0.6-Helium-SR3 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 4, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by amarsico** [comment]
Hi Kevin,
hope this helps. 
https://wiki.opendaylight.org/view/GettingStarted:Development_Environment_Setup

ODL uses a proprietary Maven repository, in the webpage you should navigate to "Edit your .m2/setting.xml" and execute the first bash command. 

Try to compile again, this should resolve your issue.

Best

**Comment by KevinPhemius** [comment]
It worked, thank you very much.
We might want to put this 'fix' in the tutorial of the ODL shim.

Best
