### ISSUE TITLE
Sequential composition with OF10

### ISSUE THREAD

**Issue by ralvarep** [fp7-netide/Engine#113]
Hi @schwabe, right now I am testing the sequential composition with OF10 with the scenario that I uploaded to the repository in _Engine/tests/parallel-switch+firewall_, but with this composition file:

```
<?xml version="1.0" ?>
<CompositionSpecification
        xmlns="http://netide.eu/schemas/compositionspecification/v1">
    <Modules>
        <Module id="Firewall" loaderIdentification="firewall.py" noFenceSupport="false">
            <CallCondition events="packetIn" datapaths="1"/>
        </Module>
        <Module id="SimpleSwitch" loaderIdentification="simple_switch.py" noFenceSupport="false">
            <CallCondition events="packetIn" datapaths="1"/>
        </Module>
    </Modules>
    <Composition>
        <ModuleCall module="SimpleSwitch"/>
        <ModuleCall module="Firewall"/>
    </Composition>
</CompositionSpecification>
```

As you can see, there are a simple switch app + firewall app in sequential mode. When I try to ping there is the following error in the core:
![captura de pantalla de 2016-07-29 11 53 26](https://cloud.githubusercontent.com/assets/3491919/17244626/16114c94-5583-11e6-89a9-a876e422b532.png)
It seems that there is some cast from PacketOut to FlowMod that generates the error.

Any idea? Thanks in advance!

**Comment by schwabe** [comment]
The code is still incomplete and as you see it cannot handle Packet out.

**Comment by ralvarep** [comment]
Ok, thanks @schwabe.

**Comment by ralvarep** [comment]
@schwabe, I continue testing the same example but ignoring the packetOuts (I have commented this line in the switch app), and as a result:
1. Firstly, when a new incoming packet arrives to the switch, a packetIn is generated and sended to the core.
2. Then, the switch app received the packetIN and generates a flowMod (with actions = output:port2)
3. And the firewall app, which is located afterwards, received the same packetIN.

I understand that as the flowMod doesn't have any action modfifying the packet, the packetIN that receives the second application is the same as the packetIN received by the first application. Is this right?

If we have an action that modify, for example, the source IP the packetIN to the second application will be modify, won't it?

Thank you.

**Comment by schwabe** [comment]
Am 29.07.16 um 17:29 schrieb Raúl Álvarez Pinilla:

> @schwabe https://github.com/schwabe, I continue testing the same
> example but ignoring the packetOuts (I have commented this line in the
> switch app), and as a result:
> 1. Firstly, when a new incoming packet arrives to the switch, a
>    packetIn is generated and sended to the core.
> 2. Then, the switch app received the packetIN and generates a flowMod
>    (with actions = output:port2)
> 3. And the firewall app, which is located afterwards, received the same
>    packetIN.
> 
> I understand that as the flowMod doesn't have any action modfifying the
> packet, the packetIN that receives the second application is the same as
> the packetIN received by the first application. Is this right?
> 
> If we have an action that modify, for example, the source IP the
> packetIN to the second application will be modify, won't it?
> 
> Thank you.

The problem with the serial composition that the semantics are not
entirely clear that should be used. There are multiple possoiblities
(See also my ARNW paper on that.)

My last knowlege on the topic for the core is that we identify the use
case which needs to use serial composition and implement a serial
composition logic that fits that use case in the core. But that work
hasn't been done yet. Hence also the strong focus on the parallel
composition in the core.

Arne
