### ISSUE TITLE
Error when launching shim-2.0

### ISSUE THREAD

**Issue by kjrrp** [fp7-netide/Engine#114]
Hello,

I have this error whend I try to launch the shim-2.0 with the python core (Simple and Advanced ProxyCore):

<pre>
ryu-manager ryu-shim.py ../ryu-backend/ryu-backend.py ../ryu-backend/tests/simple_switch.py ../ryu-backend/tests/firewall.py
loading app ryu-shim.py
loading app ../ryu-backend/ryu-backend.py
loading app ../ryu-backend/tests/simple_switch.py
loading app ../ryu-backend/tests/firewall.py
loading app ryu.controller.ofp_handler
instantiating app ryu-shim.py of RyuShim
Connecting to Core on localhost:5555...
instantiating app ../ryu-backend/tests/firewall.py of Firewall
instantiating app ../ryu-backend/ryu-backend.py of RyuBackend
Backend supported protocols: {17: [1, 3, 4], 18: []}
RYU Backend initiated: backend-ryu-3393
Connecting to Core on 127.0.0.1:5555...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/tai/NetIDE/Engine/ryu-backend/ryu-backend.py", line 200, in run
    if self.backend_announcement(self.backend) is False:
  File "/home/tai/NetIDE/Engine/ryu-backend/ryu-backend.py", line 231, in backend_announcement
    ann_message = NetIDEOps.netIDE_encode('NETIDE_MODULE_ANN', None, None, None, backend.backend_name)
  File "/usr/local/lib/python2.7/dist-packages/ryu/netide/netip.py", line 88, in netIDE_encode
    type_code = NetIDEOps.NetIDE_type[type]
KeyError: 'NETIDE_MODULE_ANN'

instantiating app ../ryu-backend/tests/simple_switch.py of SimpleSwitch
instantiating app ryu.controller.ofp_handler of OFPHandler
</pre>

Best,

Kévin

**Comment by doriguzzi** [comment]
I must update the netip.py library to the latest version. You can find it on both master and shim-2.0 branches.

**Comment by KevinPhemius** [comment]
Ok it works now.
Which composition specification is used in the tutorial?

**Comment by KevinPhemius** [comment]
> it works now.
