### ISSUE TITLE
Floodlight backend not working as specified

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#120]
Hello,

I just checked out the code for the Floodlight backend.
The reason why it needs for applications to send FLOW_MOD or PACKET_OUT is because the backend is still sending messages to the Floodlight Core pipeline instead of sending them directly to the application

``` java
public static void sendToController(ChannelFuture future, OFMessage message) {
        ChannelBuffer dcb = ChannelBuffers.dynamicBuffer();
        try {
            message.writeTo(dcb);
            future.getChannel().write(dcb);
        } catch (Exception e) {
            logger.error(e.getMessage());
        }
    }
```

The previous snippet of code (from Relay.java) sends the messages received by the backend to the pipeline. It is called by this line in NetIdeModule.java:
https://github.com/fp7-netide/Engine/blob/master/floodlight-backend/v1.2/src/main/java/net/floodlightcontroller/interceptor/NetIdeModule.java#L344

This will not work as planned for the new backends (like Ryu's).
It _should_ include code like the one form the FLbackendFenceV2 branch:

``` java
// provided that moduleId is a string for the module name (e.g. "Firewall") 
//and there is a variable somewhere mapping Floodlight moduleID (string) 
//and NetIDE Core moduleID (int). This map should be constructed during the handshake.
private void sendToController(IOFSwitch sw, OFMessage message, String moduleId){
        // SEND PACKETS DIRECTLY TO THE PIPELINE
        FloodlightContext context = new FloodlightContext();
        if(moduleId.isEmpty()){
            // send to all modules
            context=null;
            floodlightProvider.handleMessage(sw,message,context); // Here we can use Relay.sendToController
        }else{
            // NetIDE composition, send to a specific module
            List<IOFMessageListener> listeners = null;
            Map<OFType,List<IOFMessageListener>> messageListeners = floodlightProvider.getListeners();
            if (messageListeners.containsKey(message.getType())) {
                listeners = messageListeners.get(message.getType());
            }
            for (IOFMessageListener listener : listeners) {
                if (moduleId.equals(listener.getName())) {
                    listener.receive(sw, message, context);
                    // TODO : the code for sending the FENCE should go here
                } else {
                    // TODO : the backend asked for an unknown application. Send an error?
                }
            }
        }
    }
```

Otherwise this is still the "old" behavior of the backend plus some FENCE support but not complete.
UC3 (and 4) will **never** work with this version of the backend.

Best,

Kévin

**Comment by peppepetra** [comment]
Hi @KevinPhemius 

I am debugging an error of the FL Backend that appears when using the solution that you propose for the Fence Mechanism.
The error is the following:

```
Exception in thread "ZeroMQBasedConnector Receive Loop" java.lang.NullPointerException
    at net.floodlightcontroller.learningswitch.LearningSwitch.createMatchFromPacket(LearningSwitch.java:384)
    at net.floodlightcontroller.learningswitch.LearningSwitch.processPacketInMessage(LearningSwitch.java:413)
    at net.floodlightcontroller.learningswitch.LearningSwitch.receive(LearningSwitch.java:526)
    at net.floodlightcontroller.interceptor.Relay.sendToController(Relay.java:99)
    at net.floodlightcontroller.interceptor.NetIdeModule.onOpenFlowCoreMessage(NetIdeModule.java:334)
    at net.floodlightcontroller.interceptor.ZeroMQBaseConnector.run(ZeroMQBaseConnector.java:118)
    at java.lang.Thread.run(Thread.java:745)
```

If you look at the LearningSwitch code at line 384 you will see that the error is because the context we are sending with the message is empty ( `FloodlightContext context = new FloodlightContext();` )and without sending the message to the pipeline I am not able to retrieve the FloodlightContext correctly. 
Do you have any suggestion how to solve it?

Thank you.

**Comment by KevinPhemius** [comment]
Hi @peppepetra ,

it looks like LearningSwitch is using the FloodlightContext for getting the packet's payload.
In that case, instead of sending an empty context, you have to add the packet_in payload.

First create the context:

```
FloodlightContext context = new FloodlightContext();
```

Then retrieve the payload from the packet_in (pi) as an Ethernet Object (you may have to tinker with that, can't remember from the top of my head).

```
Ethernet eth = new Ethernet();
eth.deserialize(pi.getPacketData(), 0, pi.getPacketData().length);
```

An finally add it to the context:

```
IFloodlightProviderService.bcStore.put(cntx, IFloodlightProviderService.CONTEXT_PI_PAYLOAD, eth);
```

**Comment by KevinPhemius** [comment]
Fixed by (https://github.com/fp7-netide/Engine/commit/590743748497728b5004969fc06f8df655738a9b)
