### ISSUE TITLE
Floodlight Backend does not support new version of IP.

### ISSUE THREAD

**Issue by sergiotamu** [fp7-netide/Engine#122]
Hello @peppepetra,

I have been testing the FL backend. For this purpose, I have used an old FL version (v1.1 branch) that I have installed since the last time. The scenario I have tested is the following: Ryu backend + Java Core + Fl backend. In the FL Backend I received the following error: "ZeroMQBasedConnector Receive Loop" java.lang.IllegalArgumentException: Unexpected value 5...
So, this means, that the current implementation of the FL Backend does NOT support the new version of Intermediate Protocol.

Also, I have tried to install the FL Backend in the last version of the Floodlight Controller (master branch), but I couldn't compile the project properly.

Furthermore, testing the FL Backend would be much easier if there was an updated guide in Github. Because, I have a guide that you sent me in an email, but I don't know if the steps for the installation are the same or not. So, please provide an updated documentation of FL Backend in the Github.

Thanks a lot!
Sergio

**Comment by peppepetra** [comment]
Hi @sergiotamu,

on master branch you can find the latest version of FL Backend.

Clone it locally and follow the instructions at:
https://github.com/fp7-netide/Engine/blob/master/floodlight-backend/v1.2/README.md

The Readme has not been updated because it is the instructions to build and test FL backend are the same as for the previous version. What it is changed, it is the FL backend code.

Let me know of any error.

Thank you.
Giuseppe

**Comment by sergiotamu** [comment]
Hello @peppepetra,

I pulled the new code from github and I followed the instructions that you sent me the last time, but when I compile the project using `make` command I get this error:

```
ant
Buildfile: /home/netide/netide/floodlight/build.xml

init:

compile:
    [javac] Compiling 6 source files to /home/netide/netide/floodlight/target/bin
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] /home/netide/netide/floodlight/src/main/java/net/floodlightcontroller/interceptor/ModuleHandlerImpl.java:55: error: cannot find symbol
    [javac]         msg.getHeader().setNetIDEProtocolVersion(NetIDEProtocolVersion.VERSION_1_3);
    [javac]                                                                       ^
    [javac]   symbol:   variable VERSION_1_3
    [javac]   location: class NetIDEProtocolVersion
    [javac] /home/netide/netide/floodlight/src/main/java/net/floodlightcontroller/interceptor/NetIdeModule.java:70: error: cannot find symbol
    [javac]     private NetIDEProtocolVersion netIpVersion = NetIDEProtocolVersion.VERSION_1_3;
    [javac]                                                                       ^
    [javac]   symbol:   variable VERSION_1_3
    [javac]   location: class NetIDEProtocolVersion
    [javac] /home/netide/netide/floodlight/src/main/java/net/floodlightcontroller/interceptor/Relay.java:61: error: cannot find symbol
    [javac]         ofMessage.getHeader().setNetIDEProtocolVersion(NetIDEProtocolVersion.VERSION_1_3);
    [javac]                                                                             ^
    [javac]   symbol:   variable VERSION_1_3
    [javac]   location: class NetIDEProtocolVersion
    [javac] 3 errors
    [javac] 1 warning

BUILD FAILED
/home/netide/netide/floodlight/build.xml:146: Compile failed; see the compiler error output for details.

Total time: 2 seconds
make: *** [all] Error 1
```
