### ISSUE TITLE
Setup new Vagrant Box with Loader

### ISSUE THREAD

**Issue by janniclas** [fp7-netide/Engine#127]
Hi @Juanma-Sanchez ,
I am currently still testing your implementation of the verifier and I noticed that if I try to run the `install` command, on any package (e.g. on the Demo package), in a clean virtual box, your verifier terminates the process, because the the network requirements, are not met. 
But if I am not mistaken the network settings are configured and installed during the install process. So would it not be better to check only the hardware requirements when installing a package? 

Greetings,

Jan-Niclas

**Comment by Juanma-Sanchez** [comment]
Hi  @janniclas ,
You're right, checking the network requirements may not make sense, I've just changed that a few moments ago. It still bothers me that the network protocol requirements are not met, is openvswitch installed later alongside the controllers?

Best regards.

**Comment by janniclas** [comment]
Hey @Juanma-Sanchez 
Maybe it makes sense to change the install process and do the network setup during the execution of the `setup.sh`. Then your network check would make sense, even before the install of the package. I will have to check when openvswitch is installed right now. I will let you know once I found something.

**Comment by janniclas** [comment]
Hi @Juanma-Sanchez ,
So I just talked to @cstritzke and we came to the decision that it would be best to check the network settings after the install process of the package, because during that process the vm will be configured for the use of the specified packages and everything needed will be installed. 
Currently openvswitch is installed in the `installMininet.sh`.
So if you have removed the check of the network settings from the install process, this would be resolved for me.

**Comment by Juanma-Sanchez** [comment]
One last doubt @janniclas @cstritzke ,
Would it be better in your opinion to check the system requirements, network protocol included, after the package has been installed?

**Comment by janniclas** [comment]
@Juanma-Sanchez in my opinion yes, then you would verify the install process too. Trying to check anything before the install process is a bit reluctant I guess, because a lot of things that you are checking during verification are only installed during the install process. 
For example, now I can't install the Package, because the verifier tells me that java is not installed. But during the install process it would be installed. So if you want to integrate verifying inside the install command, do it after the scripts have been used. Se required software for the scripts is installed with the `setup.sh`, so you could check if this software has been installed before, but the rest, like java and stuff only after an install process.

![screen shot 2016-10-11 at 14 02 49](https://cloud.githubusercontent.com/assets/8062521/19269554/81c83e30-8fbb-11e6-95e1-930f03c709f2.png)

**Comment by Juanma-Sanchez** [comment]
@janniclas So your idea is to check only hardware requirements before the installation (and stop it there if they are not met), and check that the rest of requirements (software and network) are met after everything has been properly installed, isn't it?

**Comment by janniclas** [comment]
@Juanma-Sanchez Basically yes. 
Would be the easiest way to ensure verification with the current process. 
Or are we missing something here @cstritzke ?

**Comment by Juanma-Sanchez** [comment]
Hi,
With the latest commit the verifier should behave as we agreed on tuesday, give it a look when you have time @janniclas , please.
There is also a `check /path_to_package` option already implemented in the loader that checks all the system requirements at once.
Best regards.

**Comment by janniclas** [comment]
Hey @Juanma-Sanchez ,
worked perfectly for me thanks.
