### ISSUE TITLE
Can't build the packages

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#13]
Hello Tim,

I have the following error when I try to build the CoreImplementation packages :

<pre>
$ mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] core.api Bundle
[INFO] core.caos Bundle
[INFO] core.shimconnectivity Bundle
[INFO] core.management Bundle
[INFO] core
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building core.api Bundle 1.0.0.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for eu.netide.lib:netip:jar:1.0.0.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] core.api Bundle ................................... FAILURE [0.220s]
[INFO] core.caos Bundle .................................. SKIPPED
[INFO] core.shimconnectivity Bundle ...................... SKIPPED
[INFO] core.management Bundle ............................ SKIPPED
[INFO] core .............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.723s
[INFO] Finished at: Tue Aug 18 13:32:09 CEST 2015
[INFO] Final Memory: 17M/192M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project core.api: Could not resolve dependencies for project eu.netide.core:core.api:bundle:1.0.0.0: Failure to find eu.netide.lib:netip:jar:1.0.0.0 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
</pre>

I'm following the steps in the README.

Best,

**Comment by KevinPhemius** [comment]
A little more info perhaps.
I created a new branch to integrate the LogPub in the core.
I wanted first to make it work (CoreImplementation) before adding the new bundle.
I run into that error just after pulling the last version form the repo and running _mvn clean install_ (step 2 of the How to deploy).

Best,

**Comment by TimVinkemeier** [comment]
Hi Kevin,

my bad, I did not update the Readme yet.
The packages make use of my NetIP Java library for handling Messages of the NetIDE Intermediate Protocol. This is not currently included in the branch, because I created a pull request and wanted Roberto to have a look at it before merging it into the master branch and then back into the CoreImplementation branch.

For now, you have to check out the Java NetIP branch, do mvn clean install on that project (which will install the missing eu.netide.lib.netip bundle to your local maven repository) and after that proceed with building the bundles from the CoreImplementation branch.

As soon as the pull request is accepted, I will merge the branches accordingly and update the Readme.

Best,
Tim

**Comment by KevinPhemius** [comment]
Ok thanks.

Best,

Kévin

**Comment by KevinPhemius** [comment]
Quick update,

the tests don't pass, the path of the test file for core.caos is hardcoded to a directory in your machine.

<pre>
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] core.api Bundle ................................... SUCCESS [13.130s]
[INFO] core.caos Bundle .................................. FAILURE [3.434s]
[INFO] core.shimconnectivity Bundle ...................... SKIPPED
[INFO] core.management Bundle ............................ SKIPPED
[INFO] core .............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.136s
[INFO] Finished at: Tue Aug 18 14:11:44 CEST 2015
[INFO] Final Memory: 37M/993M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project core.caos: There are test failures.
[ERROR]
[ERROR] Please refer to D:\Work\NetIDE\git\Engine\core\core.caos\target\surefire-reports for the individual test results.
</pre>

<pre>
Path testFile = FileSystems.getDefault().getPath("C:\\Users\\timvi\\Source\\Repos\\Masterarbeit\\Engine\\core\\specification\\MinimalSpecification.xml");
        Assert.assertNotNull(testFile);
        Assert.assertTrue(testFile.toFile().exists(), "Testfile does not exist");
</pre>

I built the packages with -DskipTests for now.

Best,

Kévin

**Comment by TimVinkemeier** [comment]
Fixed the absolute paths with f17f26b.

**Comment by TimVinkemeier** [comment]
Fixed in ce5fdc6.

**Comment by KevinPhemius** [comment]
Another error since I pulled the fix(es):

<pre>
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /D:/Work/NetIDE/git/Engine/core/core.connectivity/src/main/java/eu/netide/core/connectivity/BackendManager.java:[17,8] eu.netide.core.connectivity.BackendManager is not abstract and does not override abstract method getBackend(java.lang.Integer) in eu.netide.core.api.IBackendManager
[ERROR] /D:/Work/NetIDE/git/Engine/core/core.connectivity/src/main/java/eu/netide/core/connectivity/BackendManager.java:[31,5] method does not override or implement a method from a supertype
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] core.api Bundle ................................... SUCCESS [13.422s]
[INFO] core.caos Bundle .................................. SUCCESS [2.186s]
[INFO] core.shimconnectivity Bundle ...................... FAILURE [0.265s]
[INFO] core.management Bundle ............................ SKIPPED
[INFO] core .............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.191s
[INFO] Finished at: Tue Aug 18 15:08:33 CEST 2015
[INFO] Final Memory: 40M/992M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project core.shimconnectivity: Compilation failure: Compilation failure:
[ERROR] /D:/Work/NetIDE/git/Engine/core/core.connectivity/src/main/java/eu/netide/core/connectivity/BackendManager.java:[17,8] eu.netide.core.connectivity.BackendManager is not abstract and does not override abstract method getBackend(java.lang.Integer) in eu.netide.core.api.IBackendManager
[ERROR] /D:/Work/NetIDE/git/Engine/core/core.connectivity/src/main/java/eu/netide/core/connectivity/BackendManager.java:[31,5] method does not override or implement a method from a supertype
</pre>

**Comment by TimVinkemeier** [comment]
Yeah, sorry, I am still working on this right now :smile: 
Should be fixed with 9e3da20, at least it completely builds on my machine.

**Comment by KevinPhemius** [comment]
No problem ;-)

<pre>
[INFO] core.api Bundle ................................... SUCCESS [13.534s]
[INFO] core.caos Bundle .................................. SUCCESS [3.699s]
[INFO] core.shimconnectivity Bundle ...................... SUCCESS [4.985s]
[INFO] core.management Bundle ............................ SUCCESS [1.608s]
[INFO] core .............................................. SUCCESS [0.654s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
</pre>

:+1:
