### ISSUE TITLE
source code do not match byte code when remote debugging core

### ISSUE THREAD

**Issue by Maoyuxing** [fp7-netide/Engine#134]
Hi, I met a strange issue that when I tried to remote debug core using intelligent idea IDE. It showed that the source code do not match the byte code and the debugging process did not go right. I tried to clean jar files in ~/.m2/repository/netide/core using mvn clean command and in the IDE both, then recompile and install the project. But it did not work.
There is another thing that seems strange. The core works correctly, however, I can't find file eu.netide.core/core.features/1.1.0-SNAPSHOT/xml/features in ~/.m2/repository/netide/core directory. Is that OK? 
  Very looking forward for your help! Thank you!

**Comment by schwabe** [comment]
did you update the bundles in Karaf?. Karaf often does not update them bundle:update in the karaf console works for me

**Comment by Maoyuxing** [comment]
Thank you for your suggestion, problem solved!
