### ISSUE TITLE
Where are the Objects created?

### ISSUE THREAD

**Issue by Maoyuxing** [fp7-netide/Engine#136]
Hi, I meet a strange issue that when I try to remote debug core using intelligent idea IDE. It shows that the source code do not match the byte code and the debugging process does not go right. I have tried to clean jar files in ~/.m2/repository/netide/core using mvn clean command and in the IDE both, then recompile and install the project. But it does not work.
There is another thing that seems strange. The core works correctly, however, I can't find

**Comment by Maoyuxing** [comment]
Hi, first I want to thank you again for your help before. The problem about source code byte code mismatch has been solved. I am trying to add some functions to your project and am not very familiar with karaf osgi. There are no codes in all the start() methods. How the objects are created? I hope you will not be annoyed by this silly question.

**Comment by schwabe** [comment]
karaf does not update the jars from .m2 repo unless you use the bundl:watch command.

**Comment by schwabe** [comment]
Resolved as for the other commet
