### ISSUE TITLE
Where are the objects created?/Where is the entry point of the program, core.connectivity for example

### ISSUE THREAD

**Issue by Maoyuxing** [fp7-netide/Engine#137]
Hi, first I want to thank you again for your help before. The problem about source code byte code mismatch has been solved. I am trying to add some functions to your project and am not very familiar with karaf osgi. There are no codes in all the start() methods. How the objects are created? In other words, the start() method should be the entry point of a program, however, there is nothing in it. So, where is the actual entry point of the program, core.connectivity for example. I hope you will not be annoyed by this silly question.

**Comment by schwabe** [comment]
Googling for OSGI Bundle lifecycle will help you with that and also apache blueprint. The classes are created by karaf since the blueprint.xml specifies them.

**Comment by Maoyuxing** [comment]
thank your!
