### ISSUE TITLE
import in Eclipse

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#14]
Hello,

quick question: how do you resolve the imports in eclipse?
e.g
import org.osgi.framework.BundleActivator;
or
import eu.netide.core.connectivity.ZMQ;
or
import org.zeromq.ZMQ;

these three imports are unresolved in eclipse.

(if you use Eclipse at all).

Best,

Kévin

**Comment by TimVinkemeier** [comment]
I have no idea.
I use IntelliJ IDEA, it has support for OSGi and Maven built in.
Usually the IDE should trigger Maven to download the required dependencies from Maven Central...
Maybe there are equivalent plugins available for Eclipse?!

**Comment by KevinPhemius** [comment]
I switched to IntelliJ IDEA.
I wanted to do it since forever, now it's done ;-)

**Comment by TimVinkemeier** [comment]
Best solution :+1: :laughing:
