### ISSUE TITLE
How was blueprint.xml file generated？

### ISSUE THREAD

**Issue by Maoyuxing** [fp7-netide/Engine#140]
Hi there,
First I wanna to express my gratitude to you guys for your kindly guidance. Most of my problems are solved. Now I am trying to add some functions to the core. After reading some materials, I understand how the objects are created according to blueprint.xml files. However, I can not find materials telling me how the blueprint.xmls are generated. For example, if I wanna to add a new class to the core, how should I modify blueprint.xml? I am using intellij idea and Maven. Thank you!

**Comment by schwabe** [comment]
well the files were written by hand. I suggest to refer to the blueprint documentation for that. If you need to add your new class in the blueprint.xml depends on what the new class is doing. There is no general answer for that.

**Comment by Maoyuxing** [comment]
I successfully modified your blueprint.xml file in the project and generate it in the jar. Thank you!
