### ISSUE TITLE
some problems with the keyword ParallelCall in compositionSpecification.xml

### ISSUE THREAD

**Issue by Maoyuxing** [fp7-netide/Engine#145]
Hi, I noticed if I wrote the xml file like this:
 /Modules
  Composition
    ParallelCall resolutionPolicy="priority"
        ModuleCall module="learningswitch" priority="1" /
        ModuleCall module="SimpleSwitch" priority="1" /
    /ParallelCall
  /Composition

that means, with the keyword ParallelCall, the two backends with learningswitch and simpleswitch apps running on them respectively work well.
However, if I wrote the xml file like this:
 
  Composition
	ModuleCall module="learningswitch"/
	ModuleCall module="SimpleSwitch"/
  /Composition
that means, without the keyword ParallelCall, the backends can not work properly. 
I noticed that in your code, there are different work flows for those with and without ParallelCall. I wonder what is the different? Thank you!

**Comment by schwabe** [comment]
Yes, serial composition is not really implemented that is why you are seeing the problems. See https://irtf.org/anrw/2016/anrw16-final24.pdf for more information about serial composition and why it is difficult to implement.
