### ISSUE TITLE
ONOS-backend error

### ISSUE THREAD

**Issue by whulzp** [fp7-netide/Engine#147]
I succeeded to compile the onos-backend last year  .However,now, there is always a error :
"  Failed to execute goal on project onos-app-backend: Could not resolve dependencies for project eu.netide:onos-app-backend:bundle:1.0.0-SNAPSHOT: Could not find artifact eu.netide.lib:netip:jar:1.1.0-SNAPSHOT "\
thanks @schwabe @antonis-m @amarsico @farhaven @aleckey

**Comment by schwabe** [comment]
You need to compile and install the netip library. See the README for example of the core how to do that.
