### ISSUE TITLE
Ryu-backend error

### ISSUE THREAD

**Issue by whuwzp** [fp7-netide/Engine#148]
Hi, I got a problem when I tried to use the "ryu-backend.py", while the "ryu-shim.py" was working regularly.
PROBLEM: 
- the ryu-shim.py run well, it got:
```
loading app ../Engine/ryu-shim/ryu-shim.py
loading app ryu.controller.ofp_handler
instantiating app ../Engine/ryu-shim/ryu-shim.py of RyuShim
Connecting to Core on localhost:5555...
instantiating app ryu.controller.ofp_handler of OFPHandler
```
- **However,  when I run the ryu-backend.py, the program run to completion, and it got :**
```
loading app ../Engine/ryu-backend/ryu-backend.py
instantiating app ../Engine/ryu-backend/ryu-backend.py of RyuBackend 
```
It seemed the "ryu.controller.ofp_handler" hadn't been loaded and instantiated. 

thanks @schwabe @antonis-m @amarsico @farhaven @aleckey

**Comment by ElisaRojas** [comment]
Hi @whuwzp ,

From your logs, I don't clearly see the problem... I think the backend and shim just print different logs and that's all :smiley: Or did you see any other error trace?

**Comment by whuwzp** [comment]
Thank you @ElisaRojas ,
I don't know what's wrong with my computer, it works now !
Thank you anyway !

**Comment by ElisaRojas** [comment]
No problem @whuwzp !
Glad to hear it works now :smiley:
