### ISSUE TITLE
Add handling of responses to unrequested messages in the Core (extending supported messages)

### ISSUE THREAD

**Issue by ElisaRojas** [fp7-netide/Engine#38]
Currently, the Core currently handles PacketIns and FlowMods only. 
More specifically, the Core passes unrequested messages from modules to the shim. However, if these messages expect a reply (e.g. LLDP topology request...), the Core cannot send them back to the correct module.
This should be extended (for backends and shims, but also for the tools), even as a simple pass-through module.

**Comment by doriguzzi** [comment]
This also applies to all the synchronous messages. What I implemented in the shim for Ryu was to use the backend_id as xid for the OpenFlow message.So that, when the shim gets the reply from the switch, it sends the message to the core with the correct module_id (the backend_id). The core, in turns, can send the reply to the correct backend.

**Comment by sergiotamu** [comment]
Hello @ElisaRojas , @schwabe ,

We have finished the Brussels review with a very possitive mark, so now it's time to continue improving the NetIDE =). For that reason, I think that it is very important to add the necessary logic to the Core for handling the synchronous messages which come from the Tools. In this Y3 of the project we have to finish all the tools and this feature is essential for finishing this task.

**Comment by ElisaRojas** [comment]
Yes, we need to talk about this in some WP2's telco, hopefully with everybody involved (for example @KevinPhemius as the logpub developer). Basically we need to discuss how to handle messages from/to tools and the types of messages we will be handling apart from PacketIn, PacketOut and FlowMods, because some UCs might need other messages (e.g. UC2 needs to check PortStatus).

**Comment by schwabe** [comment]
I am closing this issue since it is unspecific or implemented by the core.routing module. If something is missing, please open a more specific issue.
