### ISSUE TITLE
Ryu-Shim does install PAKET_IN rules

### ISSUE THREAD

**Issue by schwabe** [fp7-netide/Engine#49]
This is merely a behaviour obversation than a bug report. @doriguzzi should decide if this a bug or not.

I have a rather current OpenVSwitch version and running the ryu-shim against it installs no PAKET_IN rules. 

```
ininet> dpctl dump-flows
*** s1 ------------------------------------------------------------------------
NXST_FLOW reply (xid=0x4):
*** s2 ------------------------------------------------------------------------
NXST_FLOW reply (xid=0x4):
*** s3 ------------------------------------------------------------------------
NXST_FLOW reply (xid=0x4):
mininet> dpctl dump-flows
*** s1 ------------------------------------------------------------------------
NXST_FLOW reply (xid=0x4):
*** s2 ------------------------------------------------------------------------
NXST_FLOW reply (xid=0x4):
*** s3 ---------------------------------
```

On contract when running " ryu-manager simple_switch_13"

```
mininet> dpctl dump-flows
*** s1 ------------------------------------------------------------------------
NXST_FLOW reply (xid=0x4):
 cookie=0x0, duration=5.152s, table=0, n_packets=0, n_bytes=0, idle_age=5, priority=0 actions=CONTROLLER:65535
*** s2 ------------------------------------------------------------------------
NXST_FLOW reply (xid=0x4):
 cookie=0x0, duration=5.154s, table=0, n_packets=0, n_bytes=0, idle_age=5, priority=0 actions=CONTROLLER:65535
*** s3 ------------------------------------------------------------------------
NXST_FLOW reply (xid=0x4):
 cookie=0x0, duration=5.158s, table=0, n_packets=0, n_bytes=0, idle_age=5, priority=0 actions=CONTROLLER:65535
```

And my OpenVSwitch version does not generate PAKET_IN without these rules (might not be totally to OpenFlow Spec)

**Comment by ElisaRojas** [comment]
I've mentioned this in issue #50, what OF version are you using? Because I see you're executing simple_switch_13.
In my captures I see PacketOuts and FlowMods. It's true I haven't checked the switch tables though, so I don't know if it's not installing something in the end and it is just working with the PacketOut.

**Comment by schwabe** [comment]
The openvswitch supports 1.0 and 1.3 at the same time. The ryu shim seems to prefer 1.3 over 1.0. 

I actually force the OpenFlow version to be 1.0 with `sudo ovs-vsctl set bridge s1 protocols=OpenFlow10` but the behaviour of OpenVSwitch does not change.

**Comment by doriguzzi** [comment]
All the OF controllers negotiate the highest version with the switches. Therefore, if OvS supports 1.0 and 1.3, Ryu will use 1.3. @schwabe please describe better the testing setup so that I can reproduce the same behavior and see where is the bug.

--rob

**Comment by schwabe** [comment]
As said, it is a  rather current development version:

ovs-dpctl --version
ovs-dpctl (Open vSwitch) 2.3.90
Compiled Jun 18 2015 11:11:43

Consider this bug merely as a headsup

**Comment by schwabe** [comment]
I cannot reproduce that anymore.
