### ISSUE TITLE
Format error (netip libraries) when testing Java core

### ISSUE THREAD

**Issue by ElisaRojas** [fp7-netide/Engine#51]
Hi,

I'm opening a new issue, just to focus on this problem before continuing with other tests.

First of all, I tried the new core code. This time it compiled, but then I got the formatting error again :( I thought it was my fault, so I repeated the process twice more (a total of three), which is the following: 
1. Uninstalling the core from karaf
2. Updating the new Java netip library and core
3. Compiling the Java netip lib
4. Compiling the core
5. Compiling the emulator package
6. Recompiling the core
7. Starting karaf and installing the core after adding the repo

Afaik, this should be enough to be testing the new core (other times I've worked with Karaf, like with the ODL shim), this was enough. In fact, with ODL I didn't need to uninstall the module first, but I did it just in case this time.
But please tell me if this is not enough... and if so, don't read the rest of the issue. If it should be enough, then read please:

So in all of my three attemps I'm still getting the formatting error at the backend:
![formaterror](https://cloud.githubusercontent.com/assets/2779496/10972736/cbec2dc0-83da-11e5-9f7f-23d990a390c0.png)

In fact, if I try to capture traffic with the NetIDE dissector, it literally explodes (this is because @andres-beato is not handling errors in format yet). So I took the dissector out and capture traffic without it and this is what I'm seeing:

> I'm attaching 4 pictures from Hello messages: from Shim to Core, from Core to Backend, from Backend to Core and from Core to Shim. You can notice **the Core adds an extra couple of bytes** with values **0x01** and **0x00**, and this is what generates the error trace.
##### Java core

_Shim -> Core_
![java1-s-c](https://cloud.githubusercontent.com/assets/2779496/10972898/816e4ea8-83db-11e5-9a0b-f7bca669ea24.png)
_Core -> Backend_
![java2-c-b](https://cloud.githubusercontent.com/assets/2779496/10972899/867e6fd6-83db-11e5-9600-0f5d9ea43ec0.png)
_Backend -> Core_
![java3-b-c](https://cloud.githubusercontent.com/assets/2779496/10972914/9eac0d2a-83db-11e5-9cfb-836b8d36e99f.png)
_Core -> Shim_
![java4-c-s](https://cloud.githubusercontent.com/assets/2779496/10972925/aad309c8-83db-11e5-9648-1b6f1f513cb4.png)

In the meantime, this is what we can see with the Python core (captured from yesterday, which currently has a bug, but which does not give any errors in relation with formats):
##### Python core

_Shim -> Core_
![python1-s-c](https://cloud.githubusercontent.com/assets/2779496/10972960/d3e29158-83db-11e5-89a2-0b7054499539.png)
_Core -> Backend_
![python2-c-b](https://cloud.githubusercontent.com/assets/2779496/10972966/d7835c48-83db-11e5-934d-af46be8675af.png)
_Backend -> Core_
![python3-b-c](https://cloud.githubusercontent.com/assets/2779496/10972975/dd3a539e-83db-11e5-9172-3c87259abd05.png)
_Core -> Shim_
![python4-c-s](https://cloud.githubusercontent.com/assets/2779496/10972982/e2451c34-83db-11e5-8e32-0ba0b213b0e3.png)

Tests were done in both cases with one single switch and two hosts + the simple_switch.py application.

Apologies again if I'm testing old code. But I think it's compiling and loading the new one. If not, please tell me what should I do. Otherwise please check the formatting issue.

Thanks.

**Comment by schwabe** [comment]
The old modules in karaf is a serious problem. I pushed a version to that now uses -SNAPSHOT bundle versions instead of 1.0.0.0. That tells karaf that it may need to reload libararies, etc.. You might also need to type bundle:watch\* in the console if it does not automatically pick up the changes.

I also updated the README.md accordingly. Can you retest with that version?

**Comment by schwabe** [comment]
If you want to know if a module is current, the best way I found so far ist: 

```
karaf@root()> bundle:headers  netip |grep Last
Bnd-LastModified = 1446815727431
```

And then using python

```
>>> time.ctime(1446815727431/1000)
'Fri Nov  6 14:15:27 2015'
```

**Comment by ElisaRojas** [comment]
@schwabe , thanks for your help.

I checked the version with your commands and it showed 29 Oct 2015.

Therefore, I updated the code and follow the new README.md, adding the -SNAPSHOT (btw, I deleted an extra / that was in it, no problem :)), but after checking the LastModified, again 29 Oct 2015 :( So I checked more info and it should be updated either with the SNAPSHOT or with a higher version. So I tried changing the pom.xml and writing 1.0.0.1 instead, but karaf was still showing 29 Oct 2015. Finally, what I did was: `bundle:update netip`, which I read in: https://karaf.apache.org/manual/latest/commands/bundle-update.html 
And then I finally got an updated version:

```
karaf@root()> bundle:headers  netip | grep Last
Bnd-LastModified = 1446733955352
```

```
>>> time.ctime(1446733955352/1000)
'Thu Nov  5 15:32:35 2015'
```

After this, I repeated the tests with Wireshark and I still got the same formatting issues (still the extra 2 bytes -0x01 and 0x00- added in the NETIDE messages).

My conclusion, I'm a bit confused now with versions. I guess now I should be using the updated netip library, but I see 5 Nov instead of 6 (does that make sense?) and the formatting problem is still there. Any other clues? The formatting problem you solved in the last netip version was related to these extra bytes and it is supposed to be solved or was it something else?

Thanks.

**Comment by schwabe** [comment]
Did you also change/add the new repo in karaf? 

```
feature:repo-add mvn:eu.netide.core/core/1.0.0.0-SNAPSHOT/xml/features
```

```
karaf@root()> bundle:list 
START LEVEL 100 , List Threshold: 50
ID | State  | Lvl | Version          | Name                    
---------------------------------------------------------------
64 | Active |  70 | 1.0.0.0-SNAPSHOT | netip Bundle            
65 | Active |  70 | 1.0.0.0-SNAPSHOT | core.api Bundle         
66 | Active |  80 | 1.0.0.0-SNAPSHOT | core.connectivity Bundle
67 | Active |  80 | 1.0.0.0-SNAPSHOT | core.caos Bundle        
68 | Active |  80 | 1.0.0.0-SNAPSHOT | core.logpub Bundle      
69 | Active |  80 | 1.0.0.0-SNAPSHOT | core.management Bundle  
karaf@root()> 
```

**Comment by ElisaRojas** [comment]
@schwabe Yes, that's the first thing I did (I also did feature:repo-remove for the old repo just in case). However, my `bundle:list` is not showing 1.0.0.0-SNAPSHOT, but just 1.0.0.0 for all 6 bundles.

**Comment by schwabe** [comment]
err. I have no idea then. I used a karaf clean inbetween and I am not really an karaf expert so I have no idea how to upgrade. My guess is that 1.0.0.0 is a "higher" version number than 1.0.0.0-SNAPSHOT and karaf considers 1.0.0.0 to be the more current version.

**Comment by ElisaRojas** [comment]
Ok, so I basically applied bundle:update for each of the bundles (I thought the ones from the core were new, but no) until I got 5 Nov for all of them. I've tested again and still the same formatting issue.

Now my question is, should I rely on the fact that they say the LastModified is 5 Nov? Shouldn't it be 6 (today)?

I'm going to apply a karaf clean now as you mention in your last comment (silly, but I hadn't tried before).

**Comment by schwabe** [comment]
The Bnd-Last-Modified is the build date. So they are proabably really from yesterday. Also try the bundle:watch \* that upgrades all modules (if they are already -SNAPSHOT)

**Comment by ElisaRojas** [comment]
Thank you @schwabe , I'd also tried bundle:watch \* before, but nothing. So what really worked for me was just starting `karaf clean` and that was it (silly I know, but I hadn't tried this before). And finally, 6 Nov! :) And now I feel confident is today's version, because bundles show SNAPSHOT when beeing listed, etc.

And now, the bad news, the Wireshark capture is still the same, it still has the same formatting issues :(

**Comment by schwabe** [comment]
Which versions of ryu-shim are you running? The ones of the ryu-protocol-1.1, master or CoreImplementation branch? In my setup the backend receives packet_in messages.

**Comment by ElisaRojas** [comment]
I'm using the last ones from ryu-protocol-1.1 (last commit from Oct 30), but there is now a bug that @doriguzzi is trying to fix (see #42 ). Currently, the last version of Ryu-shim + PythonCore + Ryu-backend is not working either, but at least messages appear perfectly fine in Wireshark. Previous commit from that branch worked for me, maybe you have that one?

That's why I'm just focusing right now on the format and started a different thread. Once Roberto fixes the shim, we'll focus on everything. But initially, I'm seeing this formatting problem which should be fixed anyway.

**Comment by ElisaRojas** [comment]
Btw, I just checked the traces of the previous commit of ryu-protocol-1.1 (which used to work with the Python core) -just in case- and it shows the same formatting issue for the Java core. So I don't think it's a matter of the Ryu shim or backend.

**Comment by ElisaRojas** [comment]
So, the implicit summary and questions so far are:
- What combination are you using (last Ryu commit?)?
- Don't you see the formatting error when you capture traffic? If not, please tell us the combo. I've tested old core + old ryu, old core + new ryu, new core + new ryu, and a few minutes ago I just tested also new core + old ryu, and they all have the same extra bytes from the core that should not be there (which makes Wireshark crash and makes it difficult analise traces).
  Notice: with new I mean: last commit from the specific branch (either CoreImp... or ryu...) and with old: the commit before the last one.

@schwabe Please let us know, thank you.

**Comment by schwabe** [comment]
@ElisaRojas yes I am using latest version of ryu-protocol-1.1 for shim and backend.

I am mostly not capturing traffic with wireshark but relay on the debug output of ryu-shim and ryu-backend. 

For the extra bytes: the java core tends to send empty 0mq messages. (The lua ztmp wireshark dissector show them too.) The ryu shim/backend are ignoring these empty messages.

**Comment by ElisaRojas** [comment]
Thank you @schwabe . This is solved now and Wireshark does not explode anymore :smile: 
By the way, I learnt a lot about karaf from this thread, haha. Maybe everyone should check it some day, even after closing it :smile:
