### ISSUE TITLE
Decreasing the frequency of NETIDE_HELLO messages

### ISSUE THREAD

**Issue by ElisaRojas** [fp7-netide/Engine#54]
Currently, when the shim and backend connect via the Core, the VM performance slows down a lot and I think this might be due to the high amount of NETIDE_HELLO messages exchanged. The behavior is the same for the Python core and for the Java one, and it happens once the backend and shim are connected. Would it be possible to decrease the frequency? 

Thanks!

**Comment by doriguzzi** [comment]
I've just pushed a new version of shim,backend, pythoncore and netip. It also contains a fix for this issue.

**Comment by ElisaRojas** [comment]
Thank you Roberto, performance is much better now.
