### ISSUE TITLE
NetIDE message from byte array

### ISSUE THREAD

**Issue by kjrrp** [fp7-netide/Engine#56]
Hello,

there is a method to create a byte array from a NetIDE message (and Message Header) by calling _toByteRepresentation()_
Can we have a method to create a NetIDE Message _from_ a byte array (or another constructor)?
e.g

<pre>
data[ ] d; // byte array with a NetIDE Message (Header+Payload)
Message m = new Message(d);
</pre>

or

<pre>
data[ ] d; // byte array with a NetIDE Message (Header+Payload)
Message m = new Message();
m.fromByteArray(d); // fills up all fields from the byte array
</pre>

It would be easier to manipulate Message objects that way.

Best,

---

Kévin

**Comment by schwabe** [comment]
The class NetIPConverter already gets a byte array and creates a NetIde from that.

**Comment by KevinPhemius** [comment]
Oh, I didn't see that.
Thanks Arne.
