### ISSUE TITLE
Simple Dpid composition does not work

### ISSUE THREAD

**Issue by schwabe** [fp7-netide/Engine#57]
Start the core (see README), use the `core/specification/DpidPartitionExample.xml``

Sart mininet

`sudo mn --controller=remote,ip=131.234.40.44:6633 --topo=tree,2 --switch ovs,protocols=OpenFlow10`

start front and backend

`ryu-manager --ofp-tcp-listen-port 7733 ryu-backend.py tests/simple_switch.py tests/firewall.py`

`ryu-manager ryu-shim.py`

The simple configuration will relay all messages to the backend yet the ping does not work.

**Comment by ElisaRojas** [comment]
Hi @schwabe ,

I've been testing this scenario in my VM and it's kind of working for me :neutral_face: hehe. I mean, at least some pings are working... but I don't know if they make sense at all.

With your Mininet config I obtained this:
![tree](https://cloud.githubusercontent.com/assets/2779496/11877076/5ef8e90e-a4ed-11e5-8cd5-a55ab676ab82.png)

And then I tried (just out of curiosity) with a linear topology and I got this:
![linear](https://cloud.githubusercontent.com/assets/2779496/11877101/7053b04e-a4ed-11e5-921d-8d720ac8424c.png)

I haven't checked the *.xml specification file yet, so I don't know if it makes sense or not... but at least I'm seeing pings working with the Java core! :smile: 

Please let me know if this is still not working or what should I get. In case it is working for me, I have the Wireshark captures for both cases (in case you want them) and also I can be more specific about my configuration (for example, I don't have the last OVS version installed...).

**Comment by schwabe** [comment]
It works now for me:

```
mininet> pingall
*** Ping: testing ping reachability
h1 -> h2 X X 
h2 -> h1 X X 
h3 -> X X X 
h4 -> X X h3 
*** Results: 75% dropped (3/12 received)
```

The other ping packets are forbidding by the firewall.
