### ISSUE TITLE
Can't install ryu

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#59]
Hello,

I can't install Ryu on my machine.
I follow the instruction in the Readme but I have this error:

<pre>
$ python ./setup.py install
error in ryu setup command: Invalid environment marker: (python_version >= '2.7')
</pre>

My version of Python is:

<pre>
$ python -V
Python 2.7.9
</pre>

Do you have any idea?

Best,

---

Kévin

**Comment by KevinPhemius** [comment]
I had to comment these two lines 

<pre>
oslo.config>=1.6.0, <=3.0.0 ; python_version < '2.7'
oslo.config>=1.6.0 ; python_version >= '2.7'
</pre>

in _/tools/pip-requires_

**Comment by KevinPhemius** [comment]
Also you have to install

<pre>
pip install msgpack-python
</pre>

for Ryu to function properly (it's not listed in the README with the other pip packages)

**Comment by ElisaRojas** [comment]
Hi @KevinPhemius , I see you've been replying yourself :smile: 
The README is a reference, I usually check dependencies with "dpkg-checkbuilddeps" and install everything need, however, I don't remember that package...
Anyway, if it works, it works and that's all :smiley:

**Comment by sergiotamu** [comment]
I am installing in the server Ryu and I have had the same problems that Kevin, and I solved them with the solutions that he wrote. Maybe is because of the python version that we had installed, I don't know... But I remember that when I installed Ryu in my local machine I hadn't these issues... hehe
