### ISSUE TITLE
Missing class

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#60]
the class

<pre>
import net.floodlightcontroller.core.OFConnection;
</pre>

does not exist in floodlight.

**Comment by KevinPhemius** [comment]
I downloaded the latest version of FL on their github.
This class is not here anymore so the class DummySwitch.java if full of errors.

**Comment by peppepetra** [comment]
The Backend is compatible with Floodlight v1.1

**Comment by KevinPhemius** [comment]
Ok thanks.
