### ISSUE TITLE
FL Backend question

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#62]
Hi,

I can't seem to understand why is there one ModuleHandler per SwitchHandler (and thus one ModuleHandler per DummySwitch)?

Shouldn't there be one ModuleHandler for the entire backend?

Best,

---

Kévin

**Comment by peppepetra** [comment]
You are right. This is an error. I am fixing it. It should be only one for the entire backend, but in the current implementation is never used!
