### ISSUE TITLE
"empty" composition?

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#64]
There was a request I made to Tim some time ago:
How would we define an empty composition with the Core?
(Basically, using the Java Core as a ProxyCore).
## 

Kévin

**Comment by schwabe** [comment]
You only specify a single module to handle everything. E.g. core/specification/MinimalSpecificationNoFence.xml

See also core/specification/DpidPartitionExample.xml

You many need to set the noFenceSupport depending if the backend support fence or not.
