### ISSUE TITLE
Pom.xml of core/tools/emulator

### ISSUE THREAD

**Issue by ElisaRojas** [fp7-netide/Engine#75]
Currently, the master branch does not compile the emulator because `the ${project.version}` is 1.0 and not 1.1.0-SNAPSHOT. So when trying to load the dependencies: eu.netide.core and eu.netide.lib, it fails because it uses `<version>${project.version}</version>`, which is translated into `<version>1.0</version>` and those are not the current bundles for core and lib, instead that version of the bundles does not even exist.

I've manually solved the issue in my local VM by changing that ${project.version} to 1.1.0-SNAPSHOT, but I think the header of the pom.xml should be synchronized and have `<version>1.1.0-SNAPSHOT</version>` instead and I think that would fix it.

I'm not an expert in Maven, so I haven't changed the pom.xml so far, but it clearly needs to be changed to be compiled. What do you think @schwabe ?

**Comment by schwabe** [comment]
Err, I thik the emulator is not really needed anymore. At least not for loading the specification.

**Comment by ElisaRojas** [comment]
Ah, ok, I thought it was still used by your `netide:loadcomposition` command, indirectly. I thought so because I saw changes from the last few days in the project...

Anyway, do whatever you want with the project, but it would be nice if it compiled correctly at least :+1: (even if we don't use it for the general purpose of the core), don't you think? :)

**Comment by schwabe** [comment]
@ElisaRojas Yeah. I will fix that. The changes were the version number stuff which was a replace in the whole project.

Sorry about renaming the core. At one point I renamed it to check something and did not rename it back.
