### ISSUE TITLE
Cannot deploy UC3

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#8]
Hi,

which version of floodlight the code was written for.
As far as I know, UC3 won't work on 0.90, 1.0 and 1.1.
If it's 0.90, which commit was it, because I think the latest from _master_ broke the compatibility.

Best,

**Comment by antonis-m** [comment]
It's version 0.90 Let me have a look and I'll get back to you.

**Comment by antonis-m** [comment]
Kevin, which version did you use when you were developing the usecase code. One of the errors I get when trying to compile your module is that it cannot find the ImmutablePort class in the core component.

**Comment by KevinPhemius** [comment]
Hi Antonis,

I have the same error. It was a 0.90 version but the Floodlight developers changed a lot of code in that branch without changing the version (they should have use 0.90.1, 0.90.2, ...).
So I don't know which commit broke the compatibility.
I could refactor the code of the Monitor, but it will waste some time.
I can't see another solution right now.

**Comment by KevinPhemius** [comment]
I rewrote the monitor for the current master of Floodlight 0.90, and it compile without issue.
Thanks.
