### ISSUE TITLE
NetIP java library not building with target set at 1.8 + gpg key

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#88]
The NetIP java library do not compile with mvn clean install with the target at 1.8 in the pom.xml.

With the target set at 1.7, I have another error:

<pre>
[INFO] Building jar: D:\Cloudstation\Work\NetIDE\git\Engine\libraries\netip\java\target\netip-1.1.0-SNAPSHOT-javadoc.jar
[INFO]
[INFO] --- maven-gpg-plugin:1.5:sign (sign-artifacts) @ netip ---
gpg: directory `/home/kphemius/.gnupg' created
gpg: new configuration file `/home/kphemius/.gnupg/gpg.conf' created
gpg: WARNING: options in `/home/kphemius/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/home/kphemius/.gnupg/secring.gpg' created
gpg: keyring `/home/kphemius/.gnupg/pubring.gpg' created
gpg: no default secret key: secret key not available
gpg: signing failed: secret key not available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:01.898s
[INFO] Finished at: Thu Apr 07 18:26:02 CEST 2016
[INFO] Final Memory: 32M/282M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (sign-artifacts) on project netip: Exit code: 2 -> [Help 1]
</pre>

Why do we need to have signed gpg ?
## Edit: I'm on Windows, with cygwin. Never had any problem before.

Kévin

**Comment by KevinPhemius** [comment]
-Dpgp.skip-true doesn't work

**Comment by KevinPhemius** [comment]
I generated a gpg key with

<pre>
gpg --gen-key
</pre>

But I have this error now 

<pre>
[INFO] --- maven-gpg-plugin:1.5:sign (sign-artifacts) @ netip ---
gpg: cannot open tty `no tty': No such file or directory
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
</pre>

**Comment by amarsico** [comment]
Hi @KevinPhemius,
the command is this one `-Dgpg.skip=true`, compiling with 1.8 works correctly for me.

Best

**Comment by KevinPhemius** [comment]
Thank you @amarsico 
I doesn't work, it still tries to do gpg.
And I still can't build on 1.8.

<pre>
[INFO] --- maven-gpg-plugin:1.5:sign (sign-artifacts) @ netip ---
gpg: WARNING: unsafe permissions on configuration file `/cygdrive/c/Users/UX32VD/.gnupg/gpg.conf'
gpg: WARNING: unsafe enclosing directory permissions on configuration file `/cygdrive/c/Users/UX32VD/.gnupg/gpg.conf'
gpg: no default secret key: secret key not available
gpg: signing failed: secret key not available
</pre>

**Comment by sergiotamu** [comment]
Hello @KevinPhemius,

Try to do: sudo mvn clean install -Dgpg.passphrase=  "your password"

Best regards

**Comment by KevinPhemius** [comment]
Ok thanks! :+1: 

I'm leaving the issue open for the 1.7/1.8 error as it does it when I try to build the Core too.

**Comment by schwabe** [comment]
@sergiotamu don't run stuff as root

I reassign this this to @aleckey since he introduced the signing artefact.

**Comment by KevinPhemius** [comment]
Hello,

my java path wasn't set correclty so that is why the 1.8 caused errors :$
(sorry for bothering you all with such trivial stuff :P)

:+1: for solving the signing artefact

**Comment by amarsico** [comment]
@schwabe please can you change the core README and add the option `-Dskip.gpg=true` for the compilation with maven?

**Comment by schwabe** [comment]
@amarsico Can you add that? You seem to have tested that. I myself always just start a gpg-agent and let it sign the packages.
