### ISSUE TITLE
Can't launch POX

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#9]
Hi, 

I have an error when launching pox : 

sudo python ./pox.py pox_client
POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
error: uncaptured python exception, closing channel <pox_client.BackendChannel 127.0.0.1:41414 at 0xb5c60fec> (<class 'socket.error'>:[Errno 111] Connection refused [/usr/lib/python2.7/asyncore.py|read|83] [/usr/lib/python2.7/asyncore.py|handle_read_event|446] [/usr/lib/python2.7/asyncore.py|handle_connect_event|454])
INFO:core:POX 0.2.0 (carp) is up.

Do you know what is it?

Best,

**Comment by antonis-m** [comment]
Hi Kevin,

Are you sure the backend is running properly? Generally that happens when there is no listening socket on the client controller side. I'll have a look at it though

**Comment by doriguzzi** [comment]
The backend is not running. You have to start one client controller/backend
before the pox_client.

--roberto

On Mon, Jun 8, 2015 at 3:07 PM, Kévin Phemius notifications@github.com
wrote:

> Hi,
> 
> I have an error when launching pox :
> 
> sudo python ./pox.py pox_client
> POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
> error: uncaptured python exception, closing channel (:[Errno 111]
> Connection refused [/usr/lib/python2.7/asyncore.py|read|83]
> [/usr/lib/python2.7/asyncore.py|handle_read_event|446]
> [/usr/lib/python2.7/asyncore.py|handle_connect_event|454])
> INFO:core:POX 0.2.0 (carp) is up.
> 
> Do you know what is it?
> 
> Best,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fp7-netide/Engine/issues/9.

## 

# 

Roberto Doriguzzi Corin
CREATE-NET Research Center
Smart Infrastructures Area
Senior Research Engineer
Via alla Cascata 56/D - 38123 Povo Trento (Italy)
e-mail: roberto.doriguzzi@create-net.org
Tel: (+39) 0461 312429
Fax: (+39) 0461 421157
Skype: r.doriguzzi

# www.create-net.org

The information transmitted is intended only for the person or entity
to which it is addressed and may contain confidential and/or privileged
material. Any review, retransmission, dissemination or other use of, or
taking of any action in reliance upon, this information by persons or
entities other than the intended recipient is prohibited according to
the Italian Law 196/2003 of the Legislature. If you received this in
error, please contact the sender and delete the material from any
computer.

**Comment by KevinPhemius** [comment]
Yes, backend was not running.
My bad, thanks.
