### ISSUE TITLE
Error running ryu shim/backend

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#90]
Hello,

I have a problem when I try to run the Ryu shim and backend with the Java core.
I have this message from the shim:

<pre>
$ ryu-manager ryu-shim.py
loading app ryu-shim.py
loading app ryu.controller.ofp_handler
instantiating app ryu-shim.py of RyuShim
Connecting to Core on localhost:5555...
instantiating app ryu.controller.ofp_handler of OFPHandler
Received from Core: Message header: (3, 1, 6, 0, 819, 0)
Received from Core: Message body: 11:01:11:03:11:04
WARNING: It seems that the server controller is not connected to the switches/Mininet
</pre>

over and over.

The backend is stuck too:

<pre>
$ ryu-manager --ofp-tcp-listen-port 7733 ryu-backend.py tests/simple_switch.py tests/firewall.py
loading app ryu-backend.py
loading app tests/simple_switch.py
loading app tests/firewall.py
loading app ryu.controller.ofp_handler
instantiating app tests/firewall.py of Firewall
instantiating app tests/simple_switch.py of SimpleSwitch
instantiating app ryu-backend.py of RyuBackend
Backend supported protocols: {17: [1, 3, 4], 18: []}
RYU Backend initiated: backend-ryu-8546
Connecting to Core on 127.0.0.1:5555...
instantiating app ryu.controller.ofp_handler of OFPHandler
Received ack from Core: ['\x02\x05\x00\x10\x00\x00\x00\x00\x00\x00\x033\x00\x00\x00\x00\x00\x00\x00\x00backend-ryu-8546']
Received ack from Core: ['\x02\x05\x00\x08\x00\x00\x00\x00\x00\x00\x01\xde\x00\x00\x00\x00\x00\x00\x00\x00Firewall']
Received ack from Core: ['\x02\x05\x00\x0c\x00\x00\x00\x00\x00\x00\x02o\x00\x00\x00\x00\x00\x00\x00\x00SimpleSwitch']
Starting the handshake process...
Waiting for the Handshake to be completed...
Waiting for the Handshake to be completed...
Waiting for the Handshake to be completed...
</pre>

I followed the instructions from the Ryu shim and backend READMEs.

Best,

**Comment by ElisaRojas** [comment]
Hi @KevinPhemius ,

Can you give more details on the scenario? Are you running Mininet with the netide-topo example? I usually deploy components in this order:
1. Java core
2. Ryu shim
3. Mininet topology
4. Ryu backend
What order have you followed?

**Comment by KevinPhemius** [comment]
Hi, 

I followed the same order. 

I run the mininet command from the readme :

mn --topo linear, 4 --controller=remote,ip=localhost, port=6633

Mininet starts correctly (if it doesn't find the controller it prints an error) 

Best, 

Kévin 

From: Elisa Rojas

Sent: Sunday, April 10, 17:04

Subject: Re: [fp7-netide/Engine] Error running ryu shim/backend (#90)

To: fp7-netide/Engine

Cc: Kévin Phemius

Hi @KevinPhemius ,

Can you give more details on the scenario? Are you running Mininet with the netide-topo example? I usually deploy components in this order:
1. Java core
2. Ryu shim
3. Mininet topology
4. Ryu backend

What order have you followed?

**Comment by ElisaRojas** [comment]
Hi @KevinPhemius , I'd suggest to use the netide-topo (although this should not be a problem for the connection of shim+backends).

I have another question (just in case), do you load the core modules before starting anything else? Starting Karaf is not usually enough (unless you had the core module previously loaded). I'd start with `karaf clean`, the load the modules, and then the other Engine components.

If still not working, check the connection with Wireshark, because it should be as easy as that and we haven't had any other issues. Try to check the AdvancedCoreProxy.py also.

**Comment by KevinPhemius** [comment]
I can't launch the netide-topo because of this error:

<pre>
$ sudo mn --custom netide-topo.py --topo mytopo --controller=remote,ip=localhost,port=6633
--------------------------------------------------------------------------------
Caught exception. Cleaning up...
TypeError: custom() got multiple values for keyword argument 'self'
--------------------------------------------------------------------------------
</pre>

**Comment by KevinPhemius** [comment]
Yes I reload everything every time .

**Comment by ElisaRojas** [comment]
Hi @KevinPhemius , I don't really understand why you have an error with netide-topo to be honest. What Mininet + OVS installation do you have?

Please, check Wireshark as well...

**Comment by amarsico** [comment]
Hi @KevinPhemius,
I don't remember if this Mininet error was the same as mine, but try `127.0.0.1` instead of `localhost`.
I had an issue when using `localhost`, Mininet 2.2.1.

Best

**Comment by KevinPhemius** [comment]
I installed mininet with _apt-get install mininet_

<pre>
sudo mn --version
2.2.0b1
sudo ovs-vsctl show
a86ce825-ce56-4409-a453-879c4f4c1bfe
    ovs_version: "2.4.0"
</pre>

**Comment by KevinPhemius** [comment]
@amarsico the 127.0.0.1 fixed it.
Thank you.
