### ISSUE TITLE
Exception in ryu backend

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#93]
I sometimes have this error in the ryu backend.

<pre>
ryu-manager --ofp-tcp-listen-port 7733 ryu-backend.py tests/simple_switch.py tests/firewall.py
</pre>

<pre>
loading app ryu-backend.py
loading app tests/simple_switch.py
loading app tests/firewall.py
loading app ryu.controller.ofp_handler
instantiating app tests/firewall.py of Firewall
instantiating app tests/simple_switch.py of SimpleSwitch
instantiating app ryu-backend.py of RyuBackend
Backend supported protocols: {17: [1, 3, 4], 18: []}
RYU Backend initiated: backend-ryu-16743
Connecting to Core on 127.0.0.1:5555...
instantiating app ryu.controller.ofp_handler of OFPHandler
Received ack from Core: ['\x02\x05\x00\x11\x00\x00\x00\x00\x00\x00\x03\xb0\x00\x00\x00\x00\x00\x00\x00\x00backend-ryu-16743']
Received ack from Core: ['\x02\x05\x00\x08\x00\x00\x00\x00\x00\x00\x00z\x00\x00\x00\x00\x00\x00\x00\x00Firewall']
Received ack from Core: ['\x02\x05\x00\x0c\x00\x00\x00\x00\x00\x00\x03\xa6\x00\x00\x00\x00\x00\x00\x00\x00SimpleSwitch']
Starting the handshake process...
Received Message header: (3, 1, 2, 0, 944, 0)
Message type: NETIDE_HELLO
Message xid: 0
Received Message body: 11:04
Handshake completed!!!
Received Message header: (3, 17, 32, 0, 944, 3)
Message type: NETIDE_OPENFLOW
Message xid: 0
Received Message body: 04:06:00:20:00:00:03:b0:00:00:00:00:00:00:00:03:00:00:01:00:fe:00:00:00:00:00:00:4f:00:00:00:00
Sent Message header: (3, 17, 8, 0, 0, 3)
Sent Message body: 01:05:00:08:00:00:00:02
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/tai/NetIDE/Engine/ryu-backend/ryu-backend.py", line 220, in run
    self.handle_read(msg)
  File "/home/tai/NetIDE/Engine/ryu-backend/ryu-backend.py", line 304, in handle_read
    self.of_datapath.handle_event(decoded_header, message_data)
  File "/home/tai/NetIDE/Engine/ryu-backend/ryu-backend.py", line 153, in handle_event
    handler(ev)
  File "/usr/local/lib/python2.7/dist-packages/ryu/controller/ofp_handler.py", line 205, in switch_features_handler
    datapath.ports = msg.ports
AttributeError: 'OFPSwitchFeatures' object has no attribute 'ports'
</pre>

**Comment by sergiotamu** [comment]
Hello @KevinPhemius,

Which version of OpenFlow are you using for the applications and for the switches??
Maybe You are running applications with an OF version (for instance OF10) and the OVS switches emulated in mininet are using OF1.3

**Comment by ElisaRojas** [comment]
@KevinPhemius , this error usually shows up when OpenFlow versions are not matching along the Engine+Mininet, as @sergiotamu mentioned. Please be sure you use the same version for all components (either OF1.0 or OF1.3).
