### ISSUE TITLE
odl-shim does not compile

### ISSUE THREAD

**Issue by doriguzzi** [fp7-netide/Engine#95]
Hi all,

I'm trying to compile the odl-shim by following the README on github. However, I get the following error:

`[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.opendaylight.netide:netide-parent:0.1.0-SNAPSHOT: Failure to find org.opendaylight.odlparent:odlparent:pom:1.6.0-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ org.opendaylight.netide:netide-parent:0.1.0-SNAPSHOT, /media/dati/Projects/NetIDE/git_repository/Engine/odl-shim/parent/pom.xml, line 11, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.opendaylight.netide:netide-aggregator:[unknown-version] (/media/dati/Projects/NetIDE/git_repository/Engine/odl-shim/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.opendaylight.netide:netide-parent:0.1.0-SNAPSHOT: Failure to find org.opendaylight.odlparent:odlparent:pom:1.6.0-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ org.opendaylight.netide:netide-parent:0.1.0-SNAPSHOT, /media/dati/Projects/NetIDE/git_repository/Engine/odl-shim/parent/pom.xml, line 11, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException`

**Comment by ralvarep** [comment]
Hi @doriguzzi,

I had similar problems like you when I tried to use the code from this repository. 

Finally I am using the code from the [OpenDaylight repository](https://github.com/opendaylight/netide) (with the _stable/beryllium_ branch) and for the installation I suggest following the instructions of the [README of the fp7-netide repository](https://github.com/fp7-netide/Engine/tree/master/odl-shim).

**Comment by doriguzzi** [comment]
Thanks Raul, I was doing the exact same thing and at the moment is compiling (cross fingers).
@peppepetra please update code/readme on the NetIDE github and keep it aligned with the ODL repo.

Thanks

--rob

**Comment by doriguzzi** [comment]
@ralvarep I have the odl-shim running, however I do not see it connected to the core. Neither Python nor Java core. Any hint? The README on github does not say much about it.

Thanks

**Comment by peppepetra** [comment]
Is the Core running on the same machine? Can you use the Opendaylight Release (https://nexus.opendaylight.org/content/groups/public/org/opendaylight/integration/distribution-karaf/0.4.2-Beryllium-SR2/distribution-karaf-0.4.2-Beryllium-SR2.tar.gz)?
Just download it and install the shim with the command:

```
 feature:install odl-netide-rest
```

To configure the connection to the core edit the file 43-netide.xml under ODL_ROOT_DIR/etc/opendaylight/karaf

**Comment by doriguzzi** [comment]
Yes, they are running on the same machine. If I use the Ryu Shim, it can connect correctly.
I will try what you are suggesting. What is the command to use?

Thanks

**Comment by peppepetra** [comment]
I won't update the repo because we are working on the new version of the shim that will be part of the openflowplugin as it should be from the first moment.

**Comment by ElisaRojas** [comment]
Hi @doriguzzi ,

Just start the shim with `feature:install odl-netide-rest` and wait for it to appear in the log (check it with `log:display | grep netide`). Sometimes it takes a while (several minutes). I usually start first the core, then the shim and wait..... then Mininet and finally the backends.

Does the log:display shows the module loaded?

**Comment by doriguzzi** [comment]
@peppepetra I understand, but our repository is public and people that get there will find things that do not compile/work.
One option could be removing the odl-shim code (or moving it to a different branch) plus updating the README by pointing to the OpenDaylight gerrit.

Again, what is the command you referred in the post above (Just download it and install the shim with the command:) ?

**Comment by doriguzzi** [comment]
@ElisaRojas  Everything seems installed. I also see in the log that the shim is trying to connect to localhost at port 5555.

I will wait a little bit more :(

**Comment by ElisaRojas** [comment]
Hi @doriguzzi , the command that @peppepetra says is `feature:install odl-netide-rest`

Can you post your log:display?

Also post you env variables (Java and so), because for me it only worked with JDK8. With Oracle compiled, but didn't work, for example.

**Comment by peppepetra** [comment]
The problem was with  the port used for the connection to the switches. Roberto was using 6633 instead of 6644.

**Comment by doriguzzi** [comment]
Thanks again for the support @peppepetra . 
Please update the README of the odl-shim as requested in the post above, so that people won't face issues with the compilation of the code in the master branch.

Thanks
